# This is a simple workflow file
# Github workflows are written in YAML (Yet Another Markup Language)
# It nothing but a key & value pair
# being degined in 3 forms
# key & value
  # key: value
# library/dictionary
  # key: 
  #   key1: value1
  #   key2: value2
# list
  # key: 
  #   - key1: valuea
  #     key2: valueb
  #   - key1: valuec
  #     key2: valued
name: first_work
on:
  push:
     branches: 
       - main
jobs:
  first_job:
     runs-on: ubuntu-latest
     steps: 
       - name: Execute Single Line
         run: cat /etc/os-release
       - name: IP Address
         run: hostname -I
       - name: hostname
         run: hostname
  running_script_from_code:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2 # checkout/clone the repository in the runner GITHUB_WORKSPACE
       - name: run script
         run: chmod 755 script.sh && ./script.sh
       - name: running multiple line
         run: |
           chmod 755 script.sh
           ./script.sh
        
